function out = rd_DY_surf(fn)
% function out = rd_DY_surf(fn)
% 
% read wind + surf + met data generated by Discovery instrumentation
%
% out contains time, wdir_apparent, wspd_apparent, flow[1,2,3]_L2min, fluo_volt, beamc_transmittance_volt, [p,s][par, tir]_volt_times_10_to_the_minus_5
%
pkg load netcdf

# first read MET file
disp(['reading file: ' fn]); fflush(stdout);
try
	out.time = ncread(fn, 'time'); #"days since 1899-12-30 00:00:00 UTC"
	out.time = out.time + datenum([1899 12 30 00 00 00]);
	out.wdir_apparent_degs = ncread(fn, 'direct'); # "degree";
	out.wspd_apparent_m2s = ncread(fn, 'speed');  # units = "m/s";
	out.airt_degC = ncread(fn, 'airtemp'); # units = "degree_Celcius"
	out.humid_prcnt = ncread(fn, 'humid'); # units = %
catch
	disp('no wind file found');
	keyboard
end_try_catch
	
# now read SURF file
fn0 = strrep(fn, "-MET-", "-Surf-");
fn0(end-25) = '?';
fn = glob(fn0){1};
disp(['reading file: ' fn]); fflush(stdout);
try
	tmp.time = ncread(fn, 'time'); #"days since 1899-12-30 00:00:00 UTC"
	tmp.time = tmp.time + datenum([1899 12 30 00 00 00]);
	tmp.flow1_L2min = ncread(fn, 'flow1'); # flow rate
	tmp.flow2_L2min = ncread(fn, 'flow2'); # flow rate
	tmp.flow3_L2min = ncread(fn, 'flow3'); # flow rate
	tmp.fluo_volt = ncread(fn, 'fluo'); # water fluorescence
	tmp.beamc_transmittance_volt = ncread(fn, 'trans'); # "transmissibility"

	if all(tmp.time == out.time)
		fl = fieldnames(tmp);
		for ifl = 1:length(fl)
			if strcmp(fl{ifl}, "time")
				continue;
			endif
			out.(fl{ifl}) = tmp.(fl{ifl});
		endfor
	else
		keyboard
	endif
	clear tmp
	
catch
	disp('no surf file found');	
end_try_catch

	
# now read SURF file
fn0 = strrep(fn0, "-Surf-", "-Light-");
fn = glob(fn0){1};
disp(['reading file: ' fn]); fflush(stdout);
try 
	tmp.time = ncread(fn, 'time'); #"days since 1899-12-30 00:00:00 UTC"
	tmp.time = tmp.time + datenum([1899 12 30 00 00 00]);
	tmp.atmpres_mbar = ncread(fn, 'pres'); # atmospheric pressure
	tmp.ppar_volt_times_10_to_the_minus_5 = ncread(fn, 'ppar'); # port par
	tmp.spar_volt_times_10_to_the_minus_5 = ncread(fn, 'spar'); # starboard par
	tmp.ptir_volt_times_10_to_the_minus_5 = ncread(fn, 'ppar'); # port total irradiance
	tmp.stir_volt_times_10_to_the_minus_5 = ncread(fn, 'spar'); # starboard total irradiance

	if all(tmp.time == out.time)
		fl = fieldnames(tmp);
		for ifl = 1:length(fl)
			if strcmp(fl{ifl}, "time")
				continue;
			endif
			out.(fl{ifl}) = tmp.(fl{ifl});
		endfor
	else
		keyboard
	endif
	clear tmp

catch
	disp('no surf file found');	
end_try_catch	

	
	
	
	
endfunction